### ISSUE TITLE
 Great job , I have no words ! beautiful well done !

### ISSUE THREAD

**Issue by TakerOver** [ducseb/RelayPilot#1]
I'll try as soon as possible to make a version with Arduino Nano Ethernet shild and 8/16 relay , I do not know if I'll be able to do the great job you did but posterior and will share the changes , needless to say that the work you've done to me She loved.

**Comment by ducseb** [comment]
Hi,

Thx for the comment.
Have you tried your project ?  Is it working ? 

Regards.
